buildscript {
    repositories {
        maven { url = "https://files.minecraftforge.net/maven" }
        maven { url = "https://repo.spongepowered.org/repository/maven-public/" }
        maven { url = 'https://maven.parchmentmc.org' }
    }
    dependencies {
        classpath group: "net.minecraftforge.gradle", name: "ForgeGradle", version: "[6.0,6.2)", changing: true
        classpath group: "org.spongepowered", name: "mixingradle", version: "0.7-SNAPSHOT"
        classpath 'org.parchmentmc:librarian:1.+'
    }
}

apply plugin: "net.minecraftforge.gradle"
apply plugin: "eclipse"
apply plugin: 'org.parchmentmc.librarian.forgegradle'
apply plugin: "maven-publish"
apply plugin: "org.spongepowered.mixin"

mixin {
    add sourceSets.main, "${project.modId}.refmap.json"
}

version = "${project.minecraft}-${project.modVersion}"
group = "com.teamabnormals"
archivesBaseName = project.modId

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'parchment', version: '2023.09.03-1.20.1'
    accessTransformer = file("src/main/resources/META-INF/accesstransformer.cfg")
    runs {
        client {
            workingDirectory project.file("run")
            property "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"
            property "forge.logging.console.level", "debug"
            property "mixin.env.remapRefMap", "true"
            property "mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg"
            arg "-mixin.config=" + project.modId + ".mixins.json"
            mods {
                easel_does_it {
                    source sourceSets.main
                }
            }
        }
        server {
            workingDirectory project.file("run")
            property "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"
            property "forge.logging.console.level", "debug"
            property "mixin.env.remapRefMap", "true"
            property "mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg"
            arg "-mixin.config=" + project.modId + ".mixins.json"
            mods {
                easel_does_it {
                    source sourceSets.main
                }
            }
        }
        data {
            workingDirectory project.file("run")
            property "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"
            property "forge.logging.console.level", "debug"
            property "mixin.env.remapRefMap", "true"
            property "mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg"
            property "blueprint.indev", "true"
            args "--mod", project.modId, "--all", "--output", file("src/generated/resources/"), "--existing", file("src/main/resources"), "--existing-mod", "blueprint"
            mods {
                easel_does_it {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources {
    srcDir "src/generated/resources"
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    implementation fg.deobf("curse.maven:farmers-delight-398521:8007609")
    implementation fg.deobf("curse.maven:create-328085:6323270")
    implementation fg.deobf("curse.maven:farmers-respite-551453:5543547")
    implementation fg.deobf("curse.maven:miners-delight-plus-689630:5038950")
    implementation fg.deobf("curse.maven:my-nethers-delight-1003673:6529919")
    implementation fg.deobf("curse.maven:brewin-and-chewin-637808:6237884")
    implementation fg.deobf("curse.maven:frycooks-delight-1081410:5630141")
    implementation fg.deobf("curse.maven:blueprint-382216:6408581")
    implementation fg.deobf("curse.maven:atmospheric-362393:6393127")
    implementation fg.deobf("curse.maven:autumnity-365045:6151402")
    implementation fg.deobf("curse.maven:buzzier-bees-355458:6151411")
    implementation fg.deobf("curse.maven:caverns-and-chasms-438005:6040957")
    implementation fg.deobf("curse.maven:endergetic-291509:6157658")
    implementation fg.deobf("curse.maven:environmental-388992:6060255")
    implementation fg.deobf("curse.maven:neapolitan-382016:6248885")
    implementation fg.deobf("curse.maven:savage-and-ravage-381736:6040963")
    implementation fg.deobf("curse.maven:upgrade-aquatic-326895:6393133")
    implementation fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
    implementation fg.deobf("curse.maven:abnormals-delight-442719:6057626")
    implementation fg.deobf("curse.maven:spelunkery-790530:6032457")
    implementation fg.deobf("curse.maven:selene-499980:6846127")
    implementation fg.deobf("curse.maven:gallery-1173553:6321203")
    implementation fg.deobf("curse.maven:supplementaries-412082:6749363")
    implementation fg.deobf("curse.maven:haunted-harvest-541753:6032347")
    implementation fg.deobf("curse.maven:amendments-896746:6259599")

    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"
}

repositories {
    maven { url "https://maven.teamabnormals.com/" }
    maven { url "https://dvs1.progwml6.com/files/maven/" }
    maven { url "https://modmaven.k-4u.nl" }

    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        forRepositories(fg.repository) // Only add this if you're using ForgeGradle, otherwise remove this line
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = 'MinecraftForge'
        url = 'https://maven.minecraftforge.net/'

        content {
            includeGroup 'net.minecraftforge'
        }
    }
    maven {
        url "https://cursemaven.com"
    }
    maven {
        url "https://maven.blamejared.com"
        content {
            includeGroup "mezz.jei"
        }
    }

    mavenLocal()
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : project.modName,
                "Specification-Vendor"    : "Zap",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.modName,
                "Implementation-Version"  : project.modVersion,
                "Implementation-Vendor"   : "Zap",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "MixinConfigs"            : project.modId + ".mixins.json"
        ])
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            artifact jar
        }
    }
    repositories {}
}